### PR TITLE
remove the bottom padding from the donation page.

### PR DESCRIPTION
**Pull request by ihab4real**
issues: #19 

the button will still be partially visible and you'll need to scroll down to see it, but it's only this way because your phone screen is long, it looks like this for me:

image

### CODE REVIEW

**Comment by ihab4real** [comment]
unless you don't want the screen to be scrollable in the first place.

**Review by Yassa-hue — CHANGES_REQUESTED** [review]
Please remove the top padding also. Look at the `Donate Now` title:

image


Rebase the branch on master **after** you push your changes.

**Comment by ihab4real** [comment]
> Rebase the branch on master **after** you push your changes.

done, what next? push --force?

**Comment by Yassa-hue** [comment]
> done, what next? push --force?

git push --force-with-lease

@ihab4real

**Review by Yassa-hue — APPROVED** [review]
LGTM, Rebase and merge.

**Pull request merged**
